// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmwKwkw-zATXuYoU5tjGR32fI3EisKh0g',
    appId: '1:736344214600:web:2e03f1028770c1317a9c7d',
    messagingSenderId: '736344214600',
    projectId: 'score-tracker-ac',
    authDomain: 'score-tracker-ac.firebaseapp.com',
    storageBucket: 'score-tracker-ac.firebasestorage.app',
    measurementId: 'G-KQP3KRBKF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI7bAXjMdJCZCzs_5blEGW_OPcgrSh8A4',
    appId: '1:736344214600:android:bc788c9003f1b2567a9c7d',
    messagingSenderId: '736344214600',
    projectId: 'score-tracker-ac',
    storageBucket: 'score-tracker-ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzTgjjBjs6pVmKvJpWWwHch8sjp_EV6wM',
    appId: '1:736344214600:ios:991ed0f9ea487cf67a9c7d',
    messagingSenderId: '736344214600',
    projectId: 'score-tracker-ac',
    storageBucket: 'score-tracker-ac.firebasestorage.app',
    iosBundleId: 'com.example.scoreTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzTgjjBjs6pVmKvJpWWwHch8sjp_EV6wM',
    appId: '1:736344214600:ios:448d9656f987c4987a9c7d',
    messagingSenderId: '736344214600',
    projectId: 'score-tracker-ac',
    storageBucket: 'score-tracker-ac.firebasestorage.app',
    iosBundleId: 'com.gokugunz.scoreTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmwKwkw-zATXuYoU5tjGR32fI3EisKh0g',
    appId: '1:736344214600:web:7ab1a327ce1c79de7a9c7d',
    messagingSenderId: '736344214600',
    projectId: 'score-tracker-ac',
    authDomain: 'score-tracker-ac.firebaseapp.com',
    storageBucket: 'score-tracker-ac.firebasestorage.app',
    measurementId: 'G-6DLC9TQ19K',
  );
}
